spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PRUEBAS2
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: debug
    org:
      hibernate:
        type: trace
